models.py
from hashlib import md5

from bson import ObjectId
from flask_login import UserMixin
from mongoengine import Document, StringField
from werkzeug.security import generate_password_hash, check_password_hash

from api import login


@login.user_loader
def load_user(id_):
    return User.objects(id=id_).first()


class User(UserMixin, Document):

    id = StringField(primary_key=True)
    username = StringField(max_length=64, unique=True)
    email = StringField(max_length=120, unique=True)
    password_hash = StringField(max_length=128)

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def serialize(self):
        return {
            'id': self.id,
            'username': self.username,
            'email': self.email,
            'password_hash': 'private!'
        }

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(digest, size)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from models import User


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')]
    )
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.objects(username=username.data).count()
        if user != 0:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.objects(email=email.data)
        if user.count() != 0:
            raise ValidationError('Please use a different email address.')

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO

app/routes.py
from uuid import uuid1

from flask import render_template, redirect, url_for, flash
from flask_login import current_user, login_user

from api import app
from app.forms import LoginForm, RegistrationForm
from models import User


@app.route('/', methods=['GET', 'POST'])
@app.route('/index', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        return redirect(url_for('home'))

    registration_form = RegistrationForm()

    if registration_form.validate_on_submit():
        user = User(username=registration_form.username.data, email=registration_form.email.data)
        user.set_password(registration_form.password.data)  # hashes the given password
        user.id = str(uuid1())
        user.save()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('authentication.login'))

    login_form = LoginForm()

    if login_form.validate_on_submit():
        user = User.objects(username=login_form.username.data).first()
        if user is None or not user.check_password(login_form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('authentication.login'))

        login_user(user, remember=login_form.remember_me.data)
        return redirect(url_for('home'))

    return render_template('index.html', LoginForm=login_form, RegistrationForm=registration_form)


@app.route('/home')
def home():
    return render_template('home.html')

blueprints/authentication.py
from uuid import uuid1

from flask import Blueprint, redirect, url_for, render_template, flash
from flask_login import current_user, logout_user, login_user

from app.forms import RegistrationForm, LoginForm
from models import User

authenticationController = Blueprint("authentication", __name__)


@authenticationController.route("/signup", methods=['GET', 'POST'])
def signup():
    """
    Presents an anonymous user with the registration form and adds their info to the database.
    Uses user.set_password() to hash their password (instead of storing it plaintext).
    """
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)  # hashes the given password
        user.id = str(uuid1())
        user.save()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('index'))

    return render_template('registration.html', form=form)


@authenticationController.route('/login', methods=['GET', 'POST'])
def login():
    """
    Gives an anonymous user the login form and checks their credentials against users in the database.
    """
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('authentication.login'))

        login_user(user, remember=form.remember_me.data)
        return redirect(url_for('home'))

    return render_template('login.html', form=form)


@authenticationController.route('/logout')
def logout():
    """
    Logs the current_user out and redirects them to index.
    """
    logout_user()
    return redirect(url_for('index'))

blueprints/chat.py
import uuid
from collections import deque

from flask import Blueprint, flash, redirect, url_for, render_template
from flask_login import current_user
from flask_socketio import emit, join_room, close_room

from api import socketio

chatBlueprint = Blueprint("chat", __name__)

#todo: center the "go" button
#todo: fix the scroll view
#todo: interests


#todo: deploy problem -- maybe https?
#todo: user left in queue when he/she were waiting and decide to logout/disconnect

queue_map = {
    'general': deque([]),
    'oregonstate.edu': deque([]),
    'iu.edu': deque([]),
    'ucdavis.edu': deque([])
}


@chatBlueprint.route("/chat")
def render_chat():
    if current_user.is_anonymous:
        flash('You need to be logged in to chat.')
        return redirect(url_for('index'))

    return render_template('social.html', username=current_user.username)


@socketio.on('message')
def message(data, methods=['GET', 'POST']):
    print(data)
    room_id = data['room']
    emit('message', data['message'], room=room_id, include_self=False)


@socketio.on('pair me')
def pairIfPossible(data, methods=['GET', 'POST']):
    # data = json.loads(data)
    queue = queue_map.get(data['org_name'], queue_map['general'])
    
    if queue and queue[0][0] == current_user.username:
        print(queue[0][0], current_user.username)
        return redirect(url_for('home'))
    elif queue:
        # we found a match
        waiting_user, room_id = queue.popleft()
        # Todo - waiting_user != data['username'] --> enqueue again
        join_room(room_id)
        info = {'p1': waiting_user, 'p2': data['username'], 'room_id': room_id}
        emit('introduction', info, room=room_id)
    else:
        # keep user in waiting queue
        room_id = str(uuid.uuid4())
        join_room(room_id)
        queue.append((data['username'], room_id))
        emit("store room", {'room_id': room_id}, room=room_id)
    print(queue_map)


@socketio.on('client disconnecting')
def disconnect_details(data):
    print(data)
    print("Test")
    room_id = data['room']
    emit('partner disconnected', room=room_id, include_self=False)
    close_room(room_id)
    queue = queue_map.get(data['org_name'], queue_map['general'])
    if queue:
        queue.popleft()


@socketio.on('disconnect')
def test_disconnect():
    print("Client has disconnected!")

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ '../config.py'.basedir }}/static/css/style.css">

    <title>{% block title %} {% endblock %}</title>
  </head>

  <body>
    {% include 'navbar.html' %}

    {# TODO: adjust alert settings #}
    <div class="Site-content container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}
        <div>{% block content %} {% endblock %}</div>
    </div>

    <footer class="Site-footer bg-dark">
{#        <h3 class="footer-title">Footer</h3>#}
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} Welcome to Social Ketchup {% endblock %}</h1>
    <p>You're logged in!</p>


    <div class="row" style="align-self: center">
        <div class="col-4 d-flex justify-content-center text-center">
            <p>
                Start Chatting!
            </p>
                <a href="{{ url_for('chat.render_chat') }}" class="btn btn-primary">Go</a>
        </div>
    </div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <h1>{% block title %} Welcome to Social Ketchup {% endblock %}</h1>

    <div class="row">
        <div class="card">
            <div class="card-container">
                {% with form=LoginForm %}
                    {{ wtf.quick_form(form) }}
                {% endwith %}
            </div>
        </div>
        <div class="card">
            <div class="card-container">
                {% with form=RegistrationForm %}
                    {{ wtf.quick_form(form) }}
                {% endwith %}
            </div>
        </div>
    </div>

{#    <script>#}
{#        const flipCardContainer = document.querySelector(".flip-card-container");#}
{#        flipCardContainer.addEventListener("click", function() {#}
{#           flipCardContainer.classList.toggle("flip");#}
{#        });#}
{#    </script>#}

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

<h1>{% block title %} Login {% endblock %}</h1>

    <div class="container">
        {{ wtf.quick_form(form) }}
    </div>

{% endblock %}

templates/navbar.html
<link rel="stylesheet" href="{{ '../config.py'.basedir }}/static/css/navbar.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.1/socket.io.js"></script>

<script>
  function setCookie(name,value,days) {
    var expires = "";
    if (days) {
        var date = new Date();
        date.setTime(date.getTime() + (days*24*60*60*1000));
        expires = "; expires=" + date.toUTCString();
    }
    document.cookie = name + "=" + (value || "")  + expires + "; path=/";
}
function getCookie(name) {
    var nameEQ = name + "=";
    var ca = document.cookie.split(';');
    for(var i=0;i < ca.length;i++) {
        var c = ca[i];
        while (c.charAt(0)==' ') c = c.substring(1,c.length);
        if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
    }
    return null;
}
  function disconnect(){
    var socket = io.connect('https://' + document.domain);
    Cook
    socket.emit('client disconnecting', {'room':getCookie('curr_room'), 'org_name':'stanford.edu'});

  }
</script>
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('index')}}">
        Social Ketchup
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
          <li class="nav-item">
              <a class="nav-link" href="#">About</a>
          </li>
      </ul>

      <ul class="nav navbar-nav ml-auto">
        {% if current_user.is_anonymous %}
            <li class="nav-item"><a class="nav-link" href="{{ url_for('authentication.login') }}">Login</a></li>
        {% else %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{{ current_user.avatar(32) }}" alt="user img">
                </a>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li><a class="dropdown-item" onclick="disconnect()" href="{{ url_for('authentication.logout') }}">Logout</a></li>
                </ul>
            </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>

templates/registration.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

<h1>{% block title %} Register {% endblock %}</h1>

    <div class="container">
        {{ wtf.quick_form(form) }}
    </div>

{% endblock %}

templates/social.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}



{% block content %}
    <link rel="stylesheet" href="../static/css/chat.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.1/socket.io.js"></script>

    <title>{% block title %}Social Ketchup{% endblock %}</title>

{#  <div class = "container">#}
{##}
{#    <div class = "leftpane"></div>#}
{#    <div class="middlepane" style="overflow-y: scroll; height:500px;">#}
{#      <div id="chat-log"></div>#}
{#      <form action="" id="message-form">#}
{#            <span>#}
{#            <button id="nextBtn" type="button" style="cursor: pointer;">Next</button>#}
{#            <span id='input-span'><input class = 'inputbox' id="message" autocomplete="off" type="text" placeholder="Type here..." required/></span>#}
{#            <button id="sendBtn" type="submit" style="cursor: pointer;">Send</button>#}
{#            </span>#}
{#      </form>#}
{#    </div>#}
{#    <div class = "rightpane"></div>#}
{#  </div>#}
    <style>
        .form button:hover,.form button:active,.form button:focus {
            background: #43A047;
        }
    </style>
    <div class="row" style="padding-top:10px;" >
        <div class="col"><hr></div>
        <div class="col-auto"><p class="h3" align="center">Chatting</p></div>
        <div class="col"><hr></div>
    </div>

    <div class="container">
        <div id="chat-log" class="overflow-auto msgs"></div>
        <form action="" id="message-form">
            <button id="nextBtn" class="btn btn-primary" type="button" style="cursor: pointer;">Next</button>
            <span id='input-span'>
                <input type="text" class="form-control" autocomplete="off" placeholder="Type here..." aria-label="Message" id="message">
            </span>
            <button id="sendBtn" class="btn btn-success" type="submit" style="cursor: pointer;">Send</button>
        </form>
    </div>

<script type="text/javascript">

//Bugs -- Empty message -- No scroll -- No autoscroll

$(function() {
    $(window).bind('beforeunload', function() {
        setTimeout(function() {
            setTimeout(function() {
            }, 1000);
        },1);
        return 'are you sure';
    });
}); 


  const you = "You: "
  const stranger = "Stranger: "

  var form = document.getElementById("message-form");
  const send = document.getElementById('sendBtn')
  const text = document.getElementById('message')
  const chats = document.getElementById('chat-log')
  const next = document.getElementById('nextBtn')
  var curr_room = null
  text.focus()
  // var connectionString = "wss://social-ketchup.herokuapp.com/socket.io/?EIO=4&transport=websocket"
  var socket = io.connect('https://' + document.domain); // 'http://' + document.domain + ':' + location.port


  function setCookie(name,value,days) {
    var expires = "";
    if (days) {
        var date = new Date();
        date.setTime(date.getTime() + (days*24*60*60*1000));
        expires = "; expires=" + date.toUTCString();
    }
    document.cookie = name + "=" + (value || "")  + expires + "; path=/";
}
function getCookie(name) {
    var nameEQ = name + "=";
    var ca = document.cookie.split(';');
    for(var i=0;i < ca.length;i++) {
        var c = ca[i];
        while (c.charAt(0)==' ') c = c.substring(1,c.length);
        if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
    }
    return null;
}
  function conectToNewChat(){
    document.getElementById('chat-log').innerHTML = ''
    socket.emit('pair me', {'username': "{{ username }}", 'org_name':'stanford.edu' })
  }

  function addMessage(self, message){

    if (self =='you') $('#chat-log').append($('<li>').text( you + $('#message').val()));
    if (self == 'stranger') $('#chat-log').append($('<li>').text( stranger + message));
    if (self == 'server') $('#chat-log').append($('<li>').text( "***" + message + "***"));
    var objDiv = document.getElementById("chat-log");
    objDiv.scrollTop = objDiv.scrollHeight;
  }


  function showNewChatButton(){
    var btn = document.createElement("BUTTON");
    btn.innerHTML = 'Start New Chat'
    btn.style = "cursor: pointer;"
    chats.appendChild(btn)
    btn.addEventListener('click', (e)=>{
      conectToNewChat()
    })
  }

  /* Send button click event */
  send.addEventListener('click',(e)=>{
    e.preventDefault()
    message = document.getElementById('message').value
    message = message.trim()

    if(message.length == 0){
      console.log("emptyy!!")
      alert('Hey, you cannot send an empty message!')
      return
    }
    send.setAttribute('disabled','disabled')
    addMessage('you', message)
    const payload = {'room':curr_room, 'message':message}
    console.log(payload)
    socket.emit('message', payload, ()=>{
        send.removeAttribute('disabled')
        text.value = ''
        text.focus()
    })
    console.log("Message sent: ", message)
  })


  /* Next button click event */
  next.addEventListener('click', (e)=>{
    e.preventDefault()
    socket.emit('client disconnecting', {'room':curr_room, 'org_name':'stanford.edu'});
    conectToNewChat()

  })



  /* Send socket connection is made */
   socket.on( 'connect', function() {
     socket.emit( 'pair me', {'username': "{{ username }}", 'org_name':'stanford.edu' } )
   })



   /* When 'message' arrives */
   socket.on('message', (message)=>{
    addMessage('stranger', message)
     console.log("received message:", message)
   })




   /* 'introduction' when paired with new user */
   socket.on('introduction',(data)=>{
     //TODO: compare with self and render partner name
     console.log(data)
     p1 = data['p1']
     p2 = data['p2']
     partner = "{{username}}" == p1? p2 : p1
     addMessage('server', "Connected to " + partner + "!! Say Hello!")
     curr_room = data['room_id']
     setCookie('curr_room', data['room_id'], 1)
     console.log(curr_room)
   })

   socket.on('store room', (data)=>{
    setCookie('curr_room', data['room_id'], 1)
   })
  
   /* Partner Disconnected Event */
   socket.on('partner disconnected', ()=>{
    addMessage('server', "Stranger has disconnected. You can connect with a new partner!")
    showNewChatButton()
   })

  
   function getInterests(partnerUniqueIdentifier) {
    const url = 'https://' + document.domain + ':' + location.port + "/interests?query=" + partnerUniqueIdentifier
    fetch(url)
    .then(response => response.json())  
    .then(json => {
        console.log(json);
        //document.getElementById("partner-interests").innerHTML = JSON.stringify(json)
    })
}

      window.onbeforeunload = function () {
      socket.emit('client disconnecting', {'room':curr_room, 'org_name':'stanford.edu'});
    }
  </script>




{% endblock %}